// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Cluster struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	ApiServerUrl string    `json:"api_server_url"`
	Token        string    `json:"token"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
