// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Cluster struct {
	ID        uuid.UUID
	Name      string
	Version   string
	Provider  string
	Region    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
