// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	DeleteCluster(ctx context.Context, id uuid.UUID) error
	GetCluster(ctx context.Context, id uuid.UUID) (Cluster, error)
	ListClusters(ctx context.Context) ([]Cluster, error)
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error)
}

var _ Querier = (*Queries)(nil)
